port = 8080
ip = [ 127, 0, 0, 1 ]
key_jwt = 'badObviousTestKey'
refresh_key_jwt = 'badObviousRefreshTestKey'
bucket_name = 'bucket-lemgo-dev'
wed_domains = [ 'http://localhost:3000' ]
r2_account_id = '4677c27fd128b787355958a1b8e7ba50'
r2_image_domain = 'https://pub-0dd140002e844b669fc3a8af43962665.r2.dev/'