port = 80
ip = [ 0, 0, 0, 0 ]
key_jwt =
refresh_key_jwt = 
bucket_name = 'bucket-lemgo-prod'
wed_domains = [ 'https://www.lemgo.io', 'https://lemgo.io' ]
r2_account_id = '4677c27fd128b787355958a1b8e7ba50'
r2_image_domain = 'https://www.image.lemgo.io/'